[project]
name = "jamdict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chirptext>=0.1.2",
    "puchikarui>=0.1",
    "pytest>=9.0.2",
]
